defmodule AshEdtf.Test.Repo.Migrations.Initial do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:document_dates, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:date, :edtf, null: false)
      add(:document_id, :uuid, null: false)
    end

    create(unique_index(:document_dates, [:document_id, :date], name: "document_dates_unique_date_index"))

    create table(:documents, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:document_dates) do
      modify(
        :document_id,
        references(:documents,
          column: :id,
          name: "document_dates_document_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :delete_all
        )
      )
    end

    alter table(:documents) do
      add(:title, :text)
    end
  end

  def down do
    alter table(:documents) do
      remove(:title)
    end

    drop(constraint(:document_dates, "document_dates_document_id_fkey"))

    alter table(:document_dates) do
      modify(:document_id, :uuid)
    end

    drop(table(:documents))

    drop_if_exists(unique_index(:document_dates, [:document_id, :date], name: "document_dates_unique_date_index"))

    drop(table(:document_dates))
  end
end
