defmodule AshEdtf.Test.Repo.Migrations.InitialExtensions1 do
  @moduledoc """
  Installs any extensions that are mentioned in the repo's `installed_extensions/0` callback

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("""
    CREATE OR REPLACE FUNCTION ash_elixir_or(left BOOLEAN, in right ANYCOMPATIBLE, out f1 ANYCOMPATIBLE)
    AS $$ SELECT COALESCE(NULLIF($1, FALSE), $2) $$
    LANGUAGE SQL
    SET search_path = ''
    IMMUTABLE;
    """)

    execute("""
    CREATE OR REPLACE FUNCTION ash_elixir_or(left ANYCOMPATIBLE, in right ANYCOMPATIBLE, out f1 ANYCOMPATIBLE)
    AS $$ SELECT COALESCE($1, $2) $$
    LANGUAGE SQL
    SET search_path = ''
    IMMUTABLE;
    """)

    execute("""
    CREATE OR REPLACE FUNCTION ash_elixir_and(left BOOLEAN, in right ANYCOMPATIBLE, out f1 ANYCOMPATIBLE) AS $$
      SELECT CASE
        WHEN $1 IS TRUE THEN $2
        ELSE $1
      END $$
    LANGUAGE SQL
    SET search_path = ''
    IMMUTABLE;
    """)

    execute("""
    CREATE OR REPLACE FUNCTION ash_elixir_and(left ANYCOMPATIBLE, in right ANYCOMPATIBLE, out f1 ANYCOMPATIBLE) AS $$
      SELECT CASE
        WHEN $1 IS NOT NULL THEN $2
        ELSE $1
      END $$
    LANGUAGE SQL
    SET search_path = ''
    IMMUTABLE;
    """)

    execute("""
    CREATE OR REPLACE FUNCTION ash_trim_whitespace(arr text[])
    RETURNS text[] AS $$
    DECLARE
        start_index INT = 1;
        end_index INT = array_length(arr, 1);
    BEGIN
        WHILE start_index <= end_index AND arr[start_index] = '' LOOP
            start_index := start_index + 1;
        END LOOP;

        WHILE end_index >= start_index AND arr[end_index] = '' LOOP
            end_index := end_index - 1;
        END LOOP;

        IF start_index > end_index THEN
            RETURN ARRAY[]::text[];
        ELSE
            RETURN arr[start_index : end_index];
        END IF;
    END; $$
    LANGUAGE plpgsql
    SET search_path = ''
    IMMUTABLE;
    """)

    execute("""
    CREATE OR REPLACE FUNCTION ash_raise_error(json_data jsonb)
    RETURNS BOOLEAN AS $$
    BEGIN
        -- Raise an error with the provided JSON data.
        -- The JSON object is converted to text for inclusion in the error message.
        RAISE EXCEPTION 'ash_error: %', json_data::text;
        RETURN NULL;
    END;
    $$ LANGUAGE plpgsql
    STABLE
    SET search_path = '';
    """)

    execute("""
    CREATE OR REPLACE FUNCTION ash_raise_error(json_data jsonb, type_signal ANYCOMPATIBLE)
    RETURNS ANYCOMPATIBLE AS $$
    BEGIN
        -- Raise an error with the provided JSON data.
        -- The JSON object is converted to text for inclusion in the error message.
        RAISE EXCEPTION 'ash_error: %', json_data::text;
        RETURN NULL;
    END;
    $$ LANGUAGE plpgsql
    STABLE
    SET search_path = '';
    """)

    execute("""
    CREATE OR REPLACE FUNCTION ash_required(value ANYCOMPATIBLE, payload jsonb)
    RETURNS ANYCOMPATIBLE AS $$
    BEGIN
      IF value IS NULL THEN
        RAISE EXCEPTION 'ash_error: %', payload::text;
      END IF;

      RETURN value;
    END;
    $$ LANGUAGE plpgsql
    STABLE
    SET search_path = '';
    """)

    execute("""
    CREATE OR REPLACE FUNCTION uuid_generate_v7()
    RETURNS UUID
    AS $$
    DECLARE
      timestamp    TIMESTAMPTZ;
      microseconds INT;
    BEGIN
      timestamp    = clock_timestamp();
      microseconds = (cast(extract(microseconds FROM timestamp)::INT - (floor(extract(milliseconds FROM timestamp))::INT * 1000) AS DOUBLE PRECISION) * 4.096)::INT;

      RETURN encode(
        set_byte(
          set_byte(
            overlay(uuid_send(gen_random_uuid()) placing substring(int8send(floor(extract(epoch FROM timestamp) * 1000)::BIGINT) FROM 3) FROM 1 FOR 6
          ),
          6, (b'0111' || (microseconds >> 8)::bit(4))::bit(8)::int
        ),
        7, microseconds::bit(8)::int
      ),
      'hex')::UUID;
    END
    $$
    LANGUAGE PLPGSQL
    SET search_path = ''
    VOLATILE;
    """)

    execute("CREATE DOMAIN edtf_bound AS text\n  CHECK (VALUE IN ('closed', 'open', 'unknown'))")

    execute(
      "CREATE TYPE edtf AS (\n  value text,\n  lower bigint,\n  upper bigint,\n  lower_bound edtf_bound,\n  upper_bound edtf_bound\n)"
    )

    execute(
      "CREATE OR REPLACE FUNCTION edtf_range(value edtf)\nRETURNS int8range\nLANGUAGE sql\nIMMUTABLE STRICT PARALLEL SAFE\nAS $$ SELECT int8range((value).lower, (value).upper, '[]') $$"
    )

    execute(
      "CREATE OR REPLACE FUNCTION edtf_date_to_day(value date)\nRETURNS bigint\nLANGUAGE sql\nIMMUTABLE STRICT PARALLEL SAFE\nAS $$ SELECT (value - DATE '2000-01-01')::bigint + 730485 $$"
    )

    execute(
      "CREATE OR REPLACE FUNCTION edtf_day_to_date(day bigint)\nRETURNS date\nLANGUAGE sql\nIMMUTABLE STRICT PARALLEL SAFE\nAS $$ SELECT DATE '2000-01-01' + (day - 730485)::integer $$"
    )

    execute(
      "CREATE OR REPLACE FUNCTION edtf_day_parts(\n  day bigint,\n  OUT year bigint,\n  OUT month integer,\n  OUT day_of_month integer\n)\nLANGUAGE sql\nIMMUTABLE STRICT PARALLEL SAFE\nAS $$\n  WITH era AS (\n    SELECT day - 60 AS z, floor((day - 60)::numeric / 146097)::bigint AS era\n  ), doe AS (\n    SELECT era, z - era * 146097 AS doe FROM era\n  ), yoe AS (\n    SELECT era, doe, (doe - doe / 1460 + doe / 36524 - doe / 146096) / 365 AS yoe FROM doe\n  ), doy AS (\n    SELECT era, yoe, doe - (365 * yoe + yoe / 4 - yoe / 100) AS doy FROM yoe\n  ), mp AS (\n    SELECT era, yoe, doy, (5 * doy + 2) / 153 AS mp FROM doy\n  )\n  SELECT\n    yoe + era * 400 + CASE WHEN mp >= 10 THEN 1 ELSE 0 END,\n    (CASE WHEN mp < 10 THEN mp + 3 ELSE mp - 9 END)::integer,\n    (doy - (153 * mp + 2) / 5 + 1)::integer\n  FROM mp\n$$"
    )

    execute(
      "CREATE OR REPLACE FUNCTION edtf_day_year(day bigint)\nRETURNS bigint\nLANGUAGE sql\nIMMUTABLE STRICT PARALLEL SAFE\nAS $$ SELECT (edtf_day_parts(day)).year $$"
    )

    execute(
      "CREATE OR REPLACE FUNCTION edtf_day_month(day bigint)\nRETURNS integer\nLANGUAGE sql\nIMMUTABLE STRICT PARALLEL SAFE\nAS $$ SELECT (edtf_day_parts(day)).month $$"
    )

    execute(
      "CREATE OR REPLACE FUNCTION edtf_day_decade(day bigint)\nRETURNS bigint\nLANGUAGE sql\nIMMUTABLE STRICT PARALLEL SAFE\nAS $$ SELECT floor((edtf_day_parts(day)).year::numeric / 10)::bigint * 10 $$"
    )
  end

  def down do
    # Uncomment this if you actually want to uninstall the extensions
    # when this migration is rolled back:
    execute(
      "DROP FUNCTION IF EXISTS uuid_generate_v7(), ash_raise_error(jsonb), ash_raise_error(jsonb, ANYCOMPATIBLE), ash_elixir_and(BOOLEAN, ANYCOMPATIBLE), ash_elixir_and(ANYCOMPATIBLE, ANYCOMPATIBLE), ash_elixir_or(ANYCOMPATIBLE, ANYCOMPATIBLE), ash_elixir_or(BOOLEAN, ANYCOMPATIBLE), ash_trim_whitespace(text[]), ash_required(ANYCOMPATIBLE, jsonb)"
    )

    execute("DROP FUNCTION IF EXISTS edtf_day_decade(bigint)")
    execute("DROP FUNCTION IF EXISTS edtf_day_month(bigint)")
    execute("DROP FUNCTION IF EXISTS edtf_day_year(bigint)")
    execute("DROP FUNCTION IF EXISTS edtf_day_parts(bigint)")
    execute("DROP FUNCTION IF EXISTS edtf_day_to_date(bigint)")
    execute("DROP FUNCTION IF EXISTS edtf_date_to_day(date)")
    execute("DROP FUNCTION IF EXISTS edtf_range(edtf)")
    execute("DROP TYPE IF EXISTS edtf")
    execute("DROP DOMAIN IF EXISTS edtf_bound")
  end
end
